services:
  - type: web
    name: telegram-bot-webhook
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python telegram_bot_webhook.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: BACKEND_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: MONGO_URI
        sync: false
      - key: SENDER_EMAIL
        sync: false
      - key: SENDER_PASSWORD
        sync: false